# Generated by Django 2.0.5 on 2019-01-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnjukeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('origin_name', models.CharField(default='', max_length=500)),
                ('lng', models.DecimalField(decimal_places=4, default='', max_digits=10)),
                ('lat', models.DecimalField(decimal_places=4, default='', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bounds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lng1', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lat1', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng2', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lat2', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng3', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lat3', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lng4', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lat4', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoundsPoi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poiname', models.CharField(default='', max_length=500)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('origintag', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=1000)),
                ('currentpage', models.IntegerField()),
                ('maxpage', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.Bounds')),
            ],
        ),
        migrations.CreateModel(
            name='BoundTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CountCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.Bounds')),
                ('poitype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.BoundTag')),
            ],
        ),
        migrations.CreateModel(
            name='DataCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('line', models.CharField(default='', max_length=500)),
                ('district', models.CharField(default='', max_length=500)),
                ('center_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kwdpoi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('origintag', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=500)),
                ('keyword', models.CharField(default='', max_length=500)),
                ('pageindex', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='POIDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poiname', models.CharField(default='', max_length=500)),
                ('origintag', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=1000)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('tags', models.CharField(default='', max_length=500)),
                ('distance', models.DecimalField(decimal_places=4, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='POIDetailTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.POIDetail')),
            ],
        ),
        migrations.CreateModel(
            name='RidingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orilng', models.DecimalField(decimal_places=4, default='', max_digits=10)),
                ('orilat', models.DecimalField(decimal_places=4, default='', max_digits=10)),
                ('detlng', models.DecimalField(decimal_places=4, default='', max_digits=10)),
                ('detlat', models.DecimalField(decimal_places=4, default='', max_digits=10)),
                ('distance', models.DecimalField(decimal_places=4, default='', max_digits=65)),
                ('time', models.DecimalField(decimal_places=4, default='', max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('line', models.CharField(default='', max_length=500)),
                ('district', models.CharField(default='', max_length=500)),
                ('center_distance', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stationname',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='poidetailtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.Tag'),
        ),
        migrations.AddField(
            model_name='poidetail',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.Station'),
        ),
        migrations.AddField(
            model_name='datacheck',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.Station'),
        ),
        migrations.AddField(
            model_name='datacheck',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.Tag'),
        ),
        migrations.AddField(
            model_name='boundspoi',
            name='poitype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subInfo.BoundTag'),
        ),
    ]
